linters:
    Indentation:
        character: space
        width: 4

    LeadingZero:
        enabled: true
        style: include_zero

    SelectorFormat:
        ignored_types: element
        convention: ^((u|is|has|js)\-[a-zA-Z0-9]*|([a-zA-Z0-9]*(__[a-z0-9][a-zA-Z0-9]*)?(--[a-z0-9][a-zA-Z0-9]*)?))(\\@[a-z0-9][a-zA-Z0-9]*)?$
